# Generated by Django 5.1 on 2024-09-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaisettings',
            name='organization_id',
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='api_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='max_tokens',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='model',
            field=models.CharField(default='gpt-4o-mini', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
