# Generated by Django 5.1 on 2024-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_openaisettings_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='number_of_articles',
            field=models.IntegerField(default=0),
        ),
    ]
