# Generated by Django 5.1.1 on 2024-09-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
