# Generated by Django 5.1.1 on 2024-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='body_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='body_bot_bubble_color',
            field=models.CharField(default='#009688', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='body_font_size',
            field=models.CharField(default='16px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='body_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='body_user_bubble_color',
            field=models.CharField(default='#f0f0f0', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='chat_button_color',
            field=models.CharField(default='#009688', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='chat_button_size',
            field=models.CharField(default='40px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='chat_button_text',
            field=models.CharField(default='💬', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='container_height',
            field=models.CharField(default='500px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='container_width',
            field=models.CharField(default='400px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='header_background_color',
            field=models.CharField(default='#009688', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='header_font_size',
            field=models.CharField(default='20px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='header_text',
            field=models.CharField(default='Athena Chatbot', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='header_text_align',
            field=models.CharField(default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='header_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='input_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='input_font_size',
            field=models.CharField(default='16px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='input_placeholder',
            field=models.CharField(default='Type a message...', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='secret_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='send_button_color',
            field=models.CharField(default='#009688', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='send_button_font_size',
            field=models.CharField(default='16px', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='send_button_text',
            field=models.CharField(default='Send', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='send_button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
