# Generated by Django 5.1.1 on 2024-10-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bot_body_background_color_bot_body_bot_bubble_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='input_color',
            new_name='input_text_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='header_text',
        ),
    ]
