# Generated by Django 5.1.1 on 2024-10-16 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bot_bot_id_alter_bot_secret_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='body_background_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='body_bot_bubble_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='body_font_size',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='body_text_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='body_user_bubble_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='chat_button_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='chat_button_size',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='chat_button_text',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='container_height',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='container_width',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='header_background_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='header_font_size',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='header_text_align',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='header_text_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='input_font_size',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='input_placeholder',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='input_text_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='send_button_color',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='send_button_font_size',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='send_button_text',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='send_button_text_color',
        ),
        migrations.CreateModel(
            name='WidgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_button_color', models.CharField(default='#009688', max_length=7)),
                ('chat_button_text', models.CharField(default='💬', max_length=255)),
                ('chat_button_size', models.CharField(default='40px', max_length=10)),
                ('container_width', models.CharField(default='400px', max_length=10)),
                ('container_height', models.CharField(default='500px', max_length=10)),
                ('header_background_color', models.CharField(default='#009688', max_length=7)),
                ('header_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('header_font_size', models.CharField(default='20px', max_length=10)),
                ('header_text_align', models.CharField(default='left', max_length=10)),
                ('body_background_color', models.CharField(default='#ffffff', max_length=7)),
                ('body_text_color', models.CharField(default='#000000', max_length=7)),
                ('body_font_size', models.CharField(default='16px', max_length=10)),
                ('body_user_bubble_color', models.CharField(default='#f0f0f0', max_length=7)),
                ('body_bot_bubble_color', models.CharField(default='#009688', max_length=7)),
                ('input_placeholder', models.CharField(default='Type a message...', max_length=255)),
                ('input_text_color', models.CharField(default='#000000', max_length=7)),
                ('input_font_size', models.CharField(default='16px', max_length=10)),
                ('send_button_color', models.CharField(default='#009688', max_length=7)),
                ('send_button_text', models.CharField(default='Send', max_length=255)),
                ('send_button_font_size', models.CharField(default='16px', max_length=10)),
                ('send_button_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='api.bot')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widgets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_widgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
