# Generated by Django 5.1.1 on 2024-10-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_bot_body_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='name',
            field=models.CharField(default='Widget', max_length=255),
        ),
    ]
