# Generated by Django 5.1.1 on 2024-12-07 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_widgetsettings_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wellcome_message', models.TextField(default='Hello! How can I help you?')),
                ('domain', models.CharField(default='general', max_length=255)),
                ('subdomain', models.CharField(default='general', max_length=255)),
                ('tone', models.CharField(default='neutral', max_length=255)),
                ('max_words', models.IntegerField(default=100)),
                ('detail_level', models.CharField(default='clarificare', max_length=255)),
                ('audience_level', models.CharField(default='începător', max_length=255)),
                ('multi_language', models.CharField(default='română', max_length=255)),
                ('accept_simple_chat', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='api.bot')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
